# Generated by Django 5.0.1 on 2025-12-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_city_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_currency',
            field=models.CharField(default='AED', help_text='Preferred currency for display', max_length=3),
        ),
    ]
