# Generated by Django 5.0.1 on 2026-01-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_blocked_at',
            field=models.DateTimeField(blank=True, help_text='When account was blocked due to unverified email', null=True),
        ),
    ]
