# Generated by Django 5.2.9 on 2026-01-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_email_blocked_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_blocked_at',
        ),
    ]
