# Generated by Django 5.2.9 on 2026-01-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_email_blocked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bp_number',
            field=models.CharField(blank=True, help_text='ISO 8000 compliant universal business partner identifier', max_length=20, null=True, unique=True, verbose_name='Business Partner Number'),
        ),
    ]
