# Generated by Django 5.2.9 on 2026-01-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_bp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_currency',
            field=models.CharField(default='SAR', help_text='Preferred currency for display', max_length=3),
        ),
    ]
