"""
Django settings for CarSyncro project.
"""
# Generated by 'django-admin startproject' using Django 5.2.4.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.2/ref/settings/


from pathlib import Path
import os
from dotenv import load_dotenv

# Apply Django patches (fixes template context bug)
try:
    from . import django_patches
except ImportError:
    # Fallback for when patches are in project root
    import django_patches

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# No default fallback - SECRET_KEY MUST be set in environment
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError(
        "SECRET_KEY environment variable is not set! "
        "Run 'python update_env_security.py' to generate a secure key."
    )

# SECURITY WARNING: don't run with debug turned on in production!
# Default to False for safety - explicitly set DEBUG=True for development
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver').split(',')

# Sites framework
SITE_ID = 1

INSTALLED_APPS = [
    'django_daisy',
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.humanize',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_yasg',
    'django_filters',
    # 'django_ratelimit',  # Temporarily disabled
    'axes',
    # 'csp',  # Disabled - requires Python 3.9+
    'crispy_forms',
    
    # Local apps
    'users',
    'business_partners',
    'vehicles',
    'listings',
    'inquiries',
    'reviews',
    'subscriptions',
    'notifications',
    'admin_panel',
    'content',
    'core',
    'parts',
    'analytics',
    'finance.apps.FinanceConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'core.middleware.SessionProtectionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',  # Moved after AuthenticationMiddleware
    'core.security_middleware.GlobalRateLimitMiddleware',
    'core.security_middleware.CircuitBreakerMiddleware',
    'core.security_middleware.SecurityHeadersMiddleware',
    'core.middleware.CurrencyMiddleware',
    'business_partners.middleware.VendorAccessMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'users.middleware.UserRestrictionMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'yallamotor_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'business_partners.context_processors.vendor_access',
                'business_partners.context_processors.vendor_profile_completion',
                'parts.context_processors.cart_processor',
                'core.context_processors.currency_processor',  # Multi-currency support
                'core.context_processors.cache_clearing',  # Cache clearing flag
            ],
        },
    },
]

WSGI_APPLICATION = 'yallamotor_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', ''),
        'NAME': os.environ.get('DB_NAME', ''),
        'USER': os.environ.get('DB_USER', ''),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', ''),
        'PORT': os.environ.get('DB_PORT', ''),
    }
}

# Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'carsyncro-locmem',
        'TIMEOUT': 300,
    }
}

# Cache timeouts for different data types
CACHE_TIMEOUTS = {
    'PARTS_LIST': 300,      # 5 minutes
    'PART_DETAIL': 600,     # 10 minutes
    'CATEGORIES': 3600,     # 1 hour
    'BRANDS': 3600,         # 1 hour
    'POPULAR_PARTS': 1800,  # 30 minutes
    'SEARCH_RESULTS': 300,  # 5 minutes
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'business_partners.password_validators.StrongPasswordValidator',
        'OPTIONS': {
            'min_length': 12,
        }
    },
    {
        'NAME': 'business_partners.password_validators.PasswordHistoryValidator',
        'OPTIONS': {
            'history_count': 5,
        }
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Karachi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = os.environ.get('STATIC_URL', '/static/')
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Celery Configuration
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60

# Asset versioning for cache busting in production
# This adds content hashes to static file names (e.g., style.a1b2c3.css)
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Keep the original TEMPLATES configuration - templates are in BASE_DIR/templates
# Media files
# Absolute filesystem path to the media directory
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# URL that handles media served from MEDIA_ROOT
MEDIA_URL = '/media/'

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
FILE_UPLOAD_PERMISSIONS = 0o644

# Media storage backend selection
MEDIA_STORAGE_BACKEND = os.environ.get('MEDIA_STORAGE_BACKEND', 'local')  # local, s3, cloudinary

# Image processing settings
IMAGE_QUALITY = int(os.environ.get('IMAGE_QUALITY', 85))
IMAGE_MAX_WIDTH = int(os.environ.get('IMAGE_MAX_WIDTH', 1920))
IMAGE_MAX_HEIGHT = int(os.environ.get('IMAGE_MAX_HEIGHT', 1080))
THUMBNAIL_SIZE = (300, 300)

# Video processing settings
VIDEO_MAX_SIZE = 100 * 1024 * 1024  # 100MB
VIDEO_ALLOWED_FORMATS = ['mp4', 'mov', 'avi', 'webm']

# Allowed file types
ALLOWED_IMAGE_TYPES = ['image/jpeg', 'image/png', 'image/webp', 'image/gif']
ALLOWED_VIDEO_TYPES = ['video/mp4', 'video/quicktime', 'video/x-msvideo', 'video/webm']

# Cloud Storage Settings
# AWS S3 Configuration
USE_S3 = os.environ.get('USE_S3', 'False') == 'True'
if USE_S3:
    # AWS Settings
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', '')
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'us-east-1')
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    AWS_DEFAULT_ACL = 'public-read'
    AWS_LOCATION = 'media'
    
    # S3 Static Settings
    STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    
    # S3 Media Settings
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/'

# Cloudinary Configuration
USE_CLOUDINARY = os.environ.get('USE_CLOUDINARY', 'False') == 'True'
if USE_CLOUDINARY:
    import cloudinary
    import cloudinary.uploader
    import cloudinary.api
    
    cloudinary.config(
        cloud_name=os.environ.get('CLOUDINARY_CLOUD_NAME', ''),
        api_key=os.environ.get('CLOUDINARY_API_KEY', ''),
        api_secret=os.environ.get('CLOUDINARY_API_SECRET', ''),
        secure=True
    )
    
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'users.User'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'core.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# JWT settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# Frontend URL for email verification and password reset links
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:8000')

# Site URL for email notifications and admin links
SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8000')

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React development server
    "http://127.0.0.1:3000",  # Alternative localhost
    "http://localhost:3001",  # Alternative React port
    "http://127.0.0.1:3001",  # Alternative localhost
    "http://localhost:8000",  # Frontend server
    "http://127.0.0.1:8000",  # Alternative localhost
]

# For development only - can be enabled via environment variable
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'False') == 'True'

# CORS Headers Configuration
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOWED_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# CORS Preflight Max Age
CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours

# API Documentation Settings (drf-yasg)
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False,
    'JSON_EDITOR': True,
    'SUPPORTED_SUBMIT_METHODS': [
        'get',
        'post',
        'put',
        'delete',
        'patch'
    ],
    'OPERATIONS_SORTER': 'alpha',
    'TAGS_SORTER': 'alpha',
    'DOC_EXPANSION': 'none',
    'DEEP_LINKING': True,
    'SHOW_EXTENSIONS': True,
    'SHOW_COMMON_EXTENSIONS': True,
}

REDOC_SETTINGS = {
    'LAZY_RENDERING': False,
    'HIDE_HOSTNAME': False,
    'EXPAND_RESPONSES': 'all',
    'PATH_IN_MIDDLE': True,
}

# # Email settings - Default to SMTP for production readiness
# EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
# EMAIL_HOST = os.environ.get('EMAIL_HOST', 'carsyncro.com')
# EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
# EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
# EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False') == 'True'
# EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'info@carsyncro.com')
# EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'Ibtihaj12345$@')

# # Default from email
# DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL') or EMAIL_HOST_USER or 'noreply@carsyncro.com'

# Email Service Configuration
EMAIL_SERVICE_CONFIG = {
    'ENABLED': os.environ.get('EMAIL_SERVICE_ENABLED', 'True').lower() == 'true',
    'PROVIDER': os.environ.get('EMAIL_PROVIDER', 'smtp').lower(),
    'QUEUE_PROCESSING_INTERVAL': int(os.environ.get('EMAIL_QUEUE_PROCESSING_INTERVAL', 300)),
    'MAX_RETRIES': int(os.environ.get('EMAIL_MAX_RETRIES', 3)),
    'RETRY_DELAY': int(os.environ.get('EMAIL_RETRY_DELAY', 300)),
    'BATCH_SIZE': int(os.environ.get('EMAIL_BATCH_SIZE', 50)),
}

# Fallback to Django's email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'carsyncro.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False').lower() == 'true'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'info@carsyncro.com')


# Email notification settings
ENABLE_INQUIRY_EMAIL_NOTIFICATIONS = os.environ.get('ENABLE_INQUIRY_EMAIL_NOTIFICATIONS', 'True') == 'True'

# Vendor application email settings
ENABLE_VENDOR_EMAIL_NOTIFICATIONS = os.environ.get('ENABLE_VENDOR_EMAIL_NOTIFICATIONS', 'True') == 'True'
VENDOR_ADMIN_EMAILS = os.environ.get('VENDOR_ADMIN_EMAILS', '').split(',') if os.environ.get('VENDOR_ADMIN_EMAILS') else []

# Security settings
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False') == 'True'
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'False') == 'True'

# Session configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Use database-backed sessions
SESSION_COOKIE_AGE = int(os.environ.get('SESSION_COOKIE_AGE', '1209600'))  # 2 weeks in seconds
SESSION_COOKIE_AGE_LONG = int(os.environ.get('SESSION_COOKIE_AGE_LONG', '2592000'))  # 30 days in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = False

# Rate Limiting Configuration
RATELIMIT_ENABLE = os.environ.get('RATELIMIT_ENABLE', 'True') == 'True'
RATELIMIT_USE_CACHE = 'default'
RATELIMIT_VIEW = 'listings.security.ratelimited'

# Django Axes Configuration (Brute Force Protection)
AXES_ENABLED = True  # Re-enabled with proper configuration
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # 1 hour
AXES_RESET_ON_SUCCESS = True
AXES_ENABLE_ADMIN = True
AXES_VERBOSE = False
AXES_LOCKOUT_PARAMETERS = ['ip_address', 'username']
AXES_ENABLE_ACCESS_FAILURE_LOG = False
AXES_NEVER_LOCKOUT_WHITELIST = True
AXES_NEVER_LOCKOUT_GET = True

# Authentication backends - Updated to use AxesStandaloneBackend with centralized authentication
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'core.authentication.CentralizedAuthenticationBackend',  # Centralized authentication service
    'django.contrib.auth.backends.ModelBackend',
]

# Content Security Policy (django-csp 4.0+ format)
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': ("'self'",),
        'script-src': ("'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net"),
        'style-src': ("'self'", "'unsafe-inline'", "https://fonts.googleapis.com", "https://cdn.jsdelivr.net"),
        'font-src': ("'self'", "https://fonts.gstatic.com"),
        'img-src': ("'self'", "data:", "https:"),
        'connect-src': ("'self'", "http://localhost:8001", "http://127.0.0.1:8001"),
        'frame-ancestors': ("'none'",),
        'base-uri': ("'self'",),
        'form-action': ("'self'",),
    }
}

# Additional Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
X_FRAME_OPTIONS = 'DENY'

# API Security Settings
API_RATE_LIMIT_ANONYMOUS = '100/h'
API_RATE_LIMIT_AUTHENTICATED = '1000/h'
API_RATE_LIMIT_ADMIN = '5000/h'

# Admin Panel Security Settings
ADMIN_SESSION_TIMEOUT = 30 * 60  # 30 minutes in seconds
ADMIN_MAX_CONCURRENT_SESSIONS = 3
ADMIN_REQUIRE_2FA = True
ADMIN_IP_WHITELIST = []  # Empty list means no IP restrictions
ADMIN_SUSPICIOUS_THRESHOLD = 5  # Failed attempts before marking as suspicious
ADMIN_LOCKOUT_DURATION = 60 * 60  # 1 hour in seconds
ADMIN_ACTIVITY_LOG_RETENTION_DAYS = 90

# Logging Configuration for Security Events
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'security.log'),
            'formatter': 'verbose',
        },
        'admin_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'admin_audit.log'),
            'formatter': 'verbose',
        },
        'email_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'email_notifications.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'security': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'admin_panel': {
            'handlers': ['admin_file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'axes': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'inquiries.email_service': {
            'handlers': ['email_file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'inquiries.views': {
            'handlers': ['email_file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Image Optimization Settings
IMAGE_MAX_WIDTH = 1920  # Maximum width for optimized images
IMAGE_MAX_HEIGHT = 1080  # Maximum height for optimized images
IMAGE_QUALITY = 85  # JPEG quality for optimized images (1-100)

# Thumbnail Settings
THUMBNAIL_SIZES = {
    'small': (150, 150),
    'medium': (600, 400),
    'large': (300, 300),
}

# WebP Settings
WEBP_QUALITY = 80  # WebP quality for better compression
ENABLE_WEBP = True  # Enable WebP format generation

# Crispy Forms Configuration
CRISPY_TEMPLATE_PACK = 'bootstrap4'
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap4'

# Create logs directory if it doesn't exist
os.makedirs(BASE_DIR / 'logs', exist_ok=True)
