# Generated by Django 5.2.8 on 2025-12-03 17:41

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('CHART_LINE', 'Line Chart'), ('CHART_BAR', 'Bar Chart'), ('CHART_PIE', 'Pie Chart'), ('CHART_AREA', 'Area Chart'), ('METRIC_CARD', 'Metric Card'), ('TABLE', 'Data Table'), ('PROGRESS_BAR', 'Progress Bar'), ('GAUGE', 'Gauge'), ('MAP', 'Map'), ('TEXT', 'Text Widget'), ('ALERT_LIST', 'Alert List'), ('ACTIVITY_FEED', 'Activity Feed')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(default=dict)),
                ('data_source', models.CharField(max_length=200)),
                ('refresh_interval', models.IntegerField(default=300)),
                ('position_row', models.IntegerField(default=0)),
                ('position_col', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=4)),
                ('height', models.IntegerField(default=2)),
                ('required_permission', models.CharField(blank=True, max_length=100)),
                ('required_role', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_dashboard_widgets',
                'ordering': ['position_row', 'position_col'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('CPU_USAGE', 'CPU Usage'), ('MEMORY_USAGE', 'Memory Usage'), ('DISK_USAGE', 'Disk Usage'), ('RESPONSE_TIME', 'Response Time'), ('ERROR_RATE', 'Error Rate'), ('ACTIVE_USERS', 'Active Users'), ('DB_CONNECTIONS', 'Database Connections'), ('CACHE_HIT_RATE', 'Cache Hit Rate'), ('QUEUE_SIZE', 'Queue Size'), ('BACKUP_SIZE', 'Backup Size'), ('API_CALLS', 'API Calls'), ('LOGIN_ATTEMPTS', 'Login Attempts'), ('SECURITY_EVENTS', 'Security Events'), ('COMPLIANCE_SCORE', 'Compliance Score')], max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(default='', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_system_metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_type', '-timestamp'], name='core_system_metric__6118fb_idx'), models.Index(fields=['timestamp', 'metric_type'], name='core_system_timesta_bbdbd9_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('USER_CREATE', 'User Created'), ('USER_UPDATE', 'User Updated'), ('USER_DELETE', 'User Deleted'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('USER_PASSWORD_CHANGE', 'Password Changed'), ('USER_PASSWORD_RESET', 'Password Reset'), ('USER_BAN', 'User Banned'), ('USER_UNBAN', 'User Unbanned'), ('USER_SUSPEND', 'User Suspended'), ('USER_UNSUSPEND', 'User Unsuspended'), ('USER_ROLE_CHANGE', 'User Role Changed'), ('PERMISSION_GRANT', 'Permission Granted'), ('PERMISSION_REVOKE', 'Permission Revoked'), ('ROLE_ASSIGN', 'Role Assigned'), ('ROLE_REMOVE', 'Role Removed'), ('ROLE_CREATE', 'Role Created'), ('ROLE_UPDATE', 'Role Updated'), ('ROLE_DELETE', 'Role Deleted'), ('PARTNER_CREATE', 'Business Partner Created'), ('PARTNER_UPDATE', 'Business Partner Updated'), ('PARTNER_DELETE', 'Business Partner Deleted'), ('PARTNER_APPROVE', 'Business Partner Approved'), ('PARTNER_REJECT', 'Business Partner Rejected'), ('PARTNER_SUSPEND', 'Business Partner Suspended'), ('PARTNER_UNSUSPEND', 'Business Partner Unsuspended'), ('PART_CREATE', 'Part Created'), ('PART_UPDATE', 'Part Updated'), ('PART_DELETE', 'Part Deleted'), ('PART_STOCK_UPDATE', 'Part Stock Updated'), ('PART_PRICE_UPDATE', 'Part Price Updated'), ('INVENTORY_CREATE', 'Inventory Created'), ('INVENTORY_UPDATE', 'Inventory Updated'), ('INVENTORY_DELETE', 'Inventory Deleted'), ('STOCK_MOVEMENT', 'Stock Movement'), ('STOCK_ALERT', 'Stock Alert'), ('REORDER_NOTIFICATION', 'Reorder Notification'), ('ORDER_CREATE', 'Order Created'), ('ORDER_UPDATE', 'Order Updated'), ('ORDER_CANCEL', 'Order Cancelled'), ('ORDER_COMPLETE', 'Order Completed'), ('ORDER_PAYMENT', 'Order Payment'), ('ORDER_SHIPMENT', 'Order Shipment'), ('DOCUMENT_UPLOAD', 'Document Uploaded'), ('DOCUMENT_UPDATE', 'Document Updated'), ('DOCUMENT_DELETE', 'Document Deleted'), ('DOCUMENT_APPROVE', 'Document Approved'), ('DOCUMENT_REJECT', 'Document Rejected'), ('API_CALL', 'API Call'), ('API_CREATE', 'API Create'), ('API_UPDATE', 'API Update'), ('API_DELETE', 'API Delete'), ('API_ERROR', 'API Error'), ('SECURITY_LOGIN_ATTEMPT', 'Login Attempt'), ('SECURITY_PASSWORD_RESET_REQUEST', 'Password Reset Request'), ('SECURITY_2FA_ENABLED', '2FA Enabled'), ('SECURITY_2FA_DISABLED', '2FA Disabled'), ('SECURITY_SUSPICIOUS_ACTIVITY', 'Suspicious Activity'), ('SECURITY_RATE_LIMIT_EXCEEDED', 'Rate Limit Exceeded'), ('SECURITY_PERMISSION_DENIED', 'Permission Denied'), ('SECURITY_UNAUTHORIZED_ACCESS', 'Unauthorized Access'), ('SECURITY_DATA_ACCESS', 'Data Access'), ('SECURITY_DATA_EXPORT', 'Data Export'), ('SECURITY_DATA_IMPORT', 'Data Import'), ('SYSTEM_STARTUP', 'System Startup'), ('SYSTEM_SHUTDOWN', 'System Shutdown'), ('SYSTEM_BACKUP', 'System Backup'), ('SYSTEM_RESTORE', 'System Restore'), ('SYSTEM_MAINTENANCE', 'System Maintenance'), ('SYSTEM_ERROR', 'System Error'), ('SYSTEM_WARNING', 'System Warning'), ('SYSTEM_INFO', 'System Info'), ('COMPLIANCE_CHECK', 'Compliance Check'), ('COMPLIANCE_VIOLATION', 'Compliance Violation'), ('COMPLIANCE_REPORT', 'Compliance Report'), ('COMPLIANCE_AUDIT', 'Compliance Audit'), ('ANALYTICS_VIEW', 'Analytics View'), ('ANALYTICS_EXPORT', 'Analytics Export'), ('ANALYTICS_REPORT', 'Analytics Report'), ('ANALYTICS_DASHBOARD_VIEW', 'Analytics Dashboard View'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN_ATTEMPT', 'Login Attempt')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('object_repr', models.TextField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('request_path', models.CharField(blank=True, max_length=500, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('additional_data', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_traceback', models.TextField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('retention_period_days', models.IntegerField(default=2555)),
                ('compliance_flagged', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='core_audit__user_id_1daed5_idx'), models.Index(fields=['action_type', '-timestamp'], name='core_audit__action__4b52ff_idx'), models.Index(fields=['object_type', 'object_id', '-timestamp'], name='core_audit__object__16cdab_idx'), models.Index(fields=['ip_address', '-timestamp'], name='core_audit__ip_addr_356ed9_idx'), models.Index(fields=['success', '-timestamp'], name='core_audit__success_1fbddf_idx'), models.Index(fields=['timestamp', 'action_type'], name='core_audit__timesta_112284_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('DATA_RETENTION', 'Data Retention'), ('AUDIT_LOG_RETENTION', 'Audit Log Retention'), ('USER_ACCESS_REVIEW', 'User Access Review'), ('PERMISSION_REVIEW', 'Permission Review'), ('SECURITY_SCAN', 'Security Scan'), ('BACKUP_VERIFICATION', 'Backup Verification'), ('DATA_ENCRYPTION', 'Data Encryption'), ('ACCESS_CONTROL', 'Access Control'), ('PASSWORD_POLICY', 'Password Policy'), ('SESSION_MANAGEMENT', 'Session Management'), ('DATA_PRIVACY', 'Data Privacy'), ('VENDOR_COMPLIANCE', 'Vendor Compliance'), ('INVENTORY_COMPLIANCE', 'Inventory Compliance'), ('ORDER_COMPLIANCE', 'Order Compliance')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('check_config', models.JSONField(default=dict)),
                ('schedule_config', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('results', models.JSONField(blank=True, null=True)),
                ('issues_found', models.JSONField(blank=True, null=True)),
                ('recommendations', models.JSONField(blank=True, null=True)),
                ('compliance_score', models.FloatField(blank=True, null=True)),
                ('max_score', models.FloatField(default=100.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_automated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_compliance_checks',
                'ordering': ['-last_run'],
                'indexes': [models.Index(fields=['check_type', '-last_run'], name='core_compli_check_t_1e06b6_idx'), models.Index(fields=['status', '-last_run'], name='core_compli_status_bda753_idx'), models.Index(fields=['next_run'], name='core_compli_next_ru_23314f_idx')],
            },
        ),
    ]
