# Generated by Django 5.2.8 on 2025-12-04 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        # Operations removed to fix migration history inconsistency
    ]
