# Generated by Django 5.0.1 on 2025-12-18 21:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_restore_rbac_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='ISO 4217 code (e.g., USD, SAR)', max_length=3, unique=True)),
                ('name', models.CharField(help_text='Currency name (e.g., US Dollar)', max_length=50)),
                ('symbol', models.CharField(help_text='Currency symbol (e.g., $, ﷼)', max_length=10)),
                ('symbol_position', models.CharField(choices=[('left', 'Left ($100)'), ('right', 'Right (100﷼)')], default='left', max_length=10)),
                ('decimal_places', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('thousands_separator', models.CharField(default=',', max_length=1)),
                ('decimal_separator', models.CharField(default='.', max_length=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_base', models.BooleanField(default=False, help_text='Base currency for exchange rates (USD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'db_table': 'core_currency',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code', 'is_active'], name='core_curren_code_dd6bb8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=6, help_text='1 base_currency = rate * target_currency', max_digits=12, validators=[django.core.validators.MinValueValidator(1e-06)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('api', 'Exchange Rate API'), ('manual', 'Manual Entry'), ('bank', 'Central Bank')], default='api', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('base_currency', models.ForeignKey(blank=True, help_text='Base currency (usually USD)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_rates', to='core.currency')),
                ('target_currency', models.ForeignKey(blank=True, help_text='Target currency for conversion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_rates', to='core.currency')),
            ],
            options={
                'db_table': 'core_exchange_rate',
                'ordering': ['-valid_from'],
                'indexes': [models.Index(fields=['base_currency', 'target_currency', 'is_active'], name='core_exchan_base_cu_8f1dc7_idx'), models.Index(fields=['valid_from', 'valid_to'], name='core_exchan_valid_f_762f6a_idx')],
                'unique_together': {('base_currency', 'target_currency', 'valid_from')},
            },
        ),
    ]
