# Generated by Django 5.2.9 on 2026-01-04 23:08

import django.core.serializers.json
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sequencecounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField()),
                ('event_type', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('unsubscribed', 'Unsubscribed')], max_length=15)),
                ('event_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'email_analytics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['message_id'], name='email_analy_message_fd8ec5_idx'), models.Index(fields=['event_type'], name='email_analy_event_t_eec85b_idx'), models.Index(fields=['created_at'], name='email_analy_created_a6c068_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email_type', models.CharField(help_text='Type of email (e.g., verification, welcome)', max_length=50)),
                ('to_email', models.EmailField(max_length=254)),
                ('cc_emails', models.JSONField(blank=True, default=list)),
                ('bcc_emails', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(max_length=255)),
                ('template_name', models.CharField(help_text='Name of the email template', max_length=100)),
                ('context', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reply_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment metadata')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=15)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'email_queue',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='email_queue_status_8c516c_idx'), models.Index(fields=['created_at'], name='email_queue_created_c725fe_idx'), models.Index(fields=['to_email'], name='email_queue_to_emai_cf1b5e_idx'), models.Index(fields=['email_type'], name='email_queue_email_t_94341f_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template identifier', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('subject_template', models.CharField(help_text='Subject template (supports variables)', max_length=255)),
                ('html_content', models.TextField(blank=True, help_text='HTML template content')),
                ('text_content', models.TextField(blank=True, help_text='Plain text template content')),
                ('template_type', models.CharField(choices=[('html', 'HTML'), ('text', 'Plain Text'), ('both', 'Both')], default='both', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('default_context', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'email_templates',
                'ordering': ['name', '-version'],
                'unique_together': {('name', 'version')},
            },
        ),
    ]
