# Generated by Django 5.2.9 on 2026-01-08 04:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.PositiveIntegerField()),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('escrow_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('liability_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_base', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_display', models.DecimalField(decimal_places=2, max_digits=15)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('transaction_type', models.CharField(choices=[('PAYMENT', 'Order Payment'), ('COMMISSION', 'Platform Commission'), ('PAYOUT', 'Vendor Payout'), ('REFUND', 'Customer Refund'), ('COD_SETTLEMENT', 'COD Cash Reconciliation'), ('SUBSCRIPTION', 'Vendor Subscription Fee'), ('ADJUSTMENT', 'Manual Admin Adjustment')], max_length=20)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('destination_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='finance.wallet')),
                ('source_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debits', to='finance.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscrowEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('release_date', models.DateTimeField()),
                ('is_released', models.BooleanField(default=False)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_entries', to='finance.wallet')),
            ],
            options={
                'verbose_name_plural': 'Escrow Entries',
                'ordering': ['release_date'],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['owner_content_type', 'owner_id'], name='finance_wal_owner_c_c631aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('owner_content_type', 'owner_id')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='finance_tra_transac_2a23c2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='finance_tra_created_ef4f06_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowentry',
            index=models.Index(fields=['release_date', 'is_released'], name='finance_esc_release_3ea2dd_idx'),
        ),
    ]
