# Generated by Django 5.2.9 on 2026-01-09 00:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0027_vendorprofile_bank_account_holder_name_and_more'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('PAYMENT', 'Order Payment'), ('COMMISSION', 'Platform Commission'), ('PAYOUT', 'Vendor Payout'), ('REFUND', 'Customer Refund'), ('COD_SETTLEMENT', 'COD Cash Reconciliation'), ('SUBSCRIPTION', 'Vendor Subscription Fee'), ('ESCROW_RELEASE', 'Escrow Release to Available'), ('ADJUSTMENT', 'Manual Admin Adjustment')], max_length=20),
        ),
        migrations.CreateModel(
            name='CODSettlementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='finance/cod_proofs/')),
                ('reference_number', models.CharField(help_text='Bank transaction ID or Receipt number', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved & Settled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cod_settlements', to='business_partners.businesspartner')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.wallet')),
            ],
            options={
                'verbose_name': 'COD Settlement Request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('BALANCE_ADJUSTMENT', 'Manual Balance Adjustment'), ('COMMISSION_RULE_CHANGE', 'Commission Rule Change'), ('PAYOUT_PROCESSED', 'Payout Processed'), ('BATCH_PROCESSED', 'Payment Batch Processed'), ('COD_SETTLEMENT_APPROVED', 'COD Settlement Approved'), ('ESCROW_RELEASED', 'Escrow Released'), ('ORDER_PAYMENT_PROCESSED', 'Order Payment Processed')], max_length=30)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type'], name='finance_fin_action__fc50c2_idx'), models.Index(fields=['created_at'], name='finance_fin_created_8f451f_idx')],
            },
        ),
    ]
