# Generated by Django 5.2.9 on 2026-01-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('reversed', 'Reversed'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
    ]
