# Generated by Django 5.2.9 on 2026-01-01 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_vehiclelisting_listings_ve_is_feat_639fee_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelisting',
            name='year',
            field=models.PositiveIntegerField(default=2020, help_text='Vehicle year', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2028)]),
        ),
    ]
