# Generated by Django 5.2.8 on 2025-12-04 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_adminmessage_commissionrule_messagetemplate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendornotification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='commissionrule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='commissionrule',
            name='specific_vendors',
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='paymentbatch',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='paymentbatch',
            name='payments',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='vendorbalance',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendornotification',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendorpayment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vendorpayment',
            name='related_listings',
        ),
        migrations.RemoveField(
            model_name='vendorpayment',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='AdminMessage',
        ),
        migrations.DeleteModel(
            name='CommissionRule',
        ),
        migrations.DeleteModel(
            name='MessageTemplate',
        ),
        migrations.DeleteModel(
            name='PaymentBatch',
        ),
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
        migrations.DeleteModel(
            name='VendorBalance',
        ),
        migrations.DeleteModel(
            name='VendorNotification',
        ),
        migrations.DeleteModel(
            name='VendorPayment',
        ),
    ]
