# Generated by Django 5.0.1 on 2025-12-25 23:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_commissionrule_vendorbalance_vendorpayment_and_more'),
        ('business_partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('category', models.CharField(choices=[('general', 'General'), ('approval', 'Approval Related'), ('performance', 'Performance'), ('payment', 'Payment'), ('technical', 'Technical Support'), ('complaint', 'Complaint'), ('feedback', 'Feedback')], default='general', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_messages', to='business_partners.businesspartner')),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='admin_panel.adminmessage')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_admin_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_admin_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('general', 'General'), ('approval', 'Approval Related'), ('performance', 'Performance'), ('payment', 'Payment'), ('technical', 'Technical Support'), ('complaint', 'Complaint'), ('feedback', 'Feedback')], default='general', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('variables', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VendorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('general', 'General'), ('approval', 'Approval Related'), ('performance', 'Performance'), ('payment', 'Payment'), ('technical', 'Technical Support'), ('complaint', 'Complaint'), ('feedback', 'Feedback')], default='general', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('action_text', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='admin_panel.adminmessage')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='business_partners.businesspartner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='adminmessage',
            index=models.Index(fields=['recipient', 'status'], name='admin_panel_recipie_ee06f0_idx'),
        ),
        migrations.AddIndex(
            model_name='adminmessage',
            index=models.Index(fields=['business_partner', 'status'], name='admin_panel_busines_92ab67_idx'),
        ),
        migrations.AddIndex(
            model_name='adminmessage',
            index=models.Index(fields=['created_at'], name='admin_panel_created_f6a3e9_idx'),
        ),
        migrations.AddIndex(
            model_name='vendornotification',
            index=models.Index(fields=['vendor', 'is_read'], name='admin_panel_vendor__692914_idx'),
        ),
        migrations.AddIndex(
            model_name='vendornotification',
            index=models.Index(fields=['created_at'], name='admin_panel_created_c3f168_idx'),
        ),
    ]
