# Generated by Django 5.2.9 on 2026-01-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_vendorpayment_processed_by_commissiontier'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionrule',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
