# Generated by Django 5.2.4 on 2025-10-25 09:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'City Area',
                'verbose_name_plural': 'City Areas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('maximum_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Discount Code',
                'verbose_name_plural': 'Discount Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaudiCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(max_length=100)),
                ('region_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Saudi City',
                'verbose_name_plural': 'Saudi Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('discount_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_applications', to='parts.discountcode')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount_info', to='parts.order')),
            ],
            options={
                'verbose_name': 'Order Discount',
                'verbose_name_plural': 'Order Discounts',
            },
        ),
        migrations.CreateModel(
            name='OrderShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=20)),
                ('mobile_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('address', models.TextField(help_text='House No/Building No, Street, Area')),
                ('landmark', models.CharField(blank=True, max_length=200, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_shipments', to='parts.cityarea')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_info', to='parts.order')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_shipments', to='parts.saudicity')),
            ],
            options={
                'verbose_name': 'Order Shipping',
                'verbose_name_plural': 'Order Shipping',
            },
        ),
        migrations.AddField(
            model_name='cityarea',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='parts.saudicity'),
        ),
        migrations.AlterUniqueTogether(
            name='cityarea',
            unique_together={('city', 'name')},
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('per_kg_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_delivery_days', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rates', to='parts.saudicity')),
            ],
            options={
                'verbose_name': 'Shipping Rate',
                'verbose_name_plural': 'Shipping Rates',
                'unique_together': {('city',)},
            },
        ),
    ]
