# Generated by Django 5.2.4 on 2025-10-25 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_cityarea_discountcode_saudicity_orderdiscount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='part',
            new_name='parts_part_sku_idx',
            old_name='parts_part_sku_650340_idx',
        ),
        migrations.RenameIndex(
            model_name='part',
            new_name='parts_part_active_created_idx',
            old_name='parts_part_is_acti_39a006_idx',
        ),
        migrations.RenameIndex(
            model_name='part',
            new_name='parts_part_cat_brand_idx',
            old_name='parts_part_categor_351bbc_idx',
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['name'], name='parts_brand_name_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['is_active'], name='parts_brand_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['is_active', 'name'], name='parts_brand_active_name_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['created_at'], name='parts_brand_created_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='parts_category_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='parts_category_name_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['created_at'], name='parts_category_created_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['slug'], name='parts_part_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['category'], name='parts_part_category_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['brand'], name='parts_part_brand_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['dealer'], name='parts_part_dealer_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['is_active'], name='parts_part_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['is_featured'], name='parts_part_is_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['price'], name='parts_part_price_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['quantity'], name='parts_part_quantity_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['view_count'], name='parts_part_view_count_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['created_at'], name='parts_part_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['category', 'is_active'], name='parts_part_cat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['brand', 'is_active'], name='parts_part_brand_active_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['dealer', 'is_active'], name='parts_part_dealer_active_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['is_active', 'price'], name='parts_part_active_price_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['is_active', 'quantity'], name='parts_part_active_qty_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['is_featured', 'is_active'], name='parts_part_featured_active_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['category', 'price'], name='parts_part_cat_price_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['brand', 'price'], name='parts_part_brand_price_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['name'], name='parts_part_name_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['description'], name='parts_part_desc_idx'),
        ),
    ]
