# Generated by Django 5.2.4 on 2025-11-02 11:47

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_rename_parts_part_sku_650340_idx_parts_part_sku_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='part',
            name='parts_part_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='part',
            name='parts_part_desc_idx',
        ),
        migrations.AddField(
            model_name='part',
            name='abc_indicator',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], help_text='ABC analysis indicator', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='base_unit_of_measure',
            field=models.CharField(default='EA', help_text='Base unit of measure (EA, KG, L, etc.)', max_length=10),
        ),
        migrations.AddField(
            model_name='part',
            name='division',
            field=models.CharField(blank=True, help_text='Division code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='expiration_xchpf',
            field=models.CharField(blank=True, help_text='Expiration indicator (XCHPF)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='external_material_group',
            field=models.CharField(blank=True, help_text='External material group classification', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='goods_receipt_processing_time_days',
            field=models.PositiveIntegerField(blank=True, help_text='Goods receipt processing time in days', null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Gross weight in kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='manufacturer_oem_number',
            field=models.CharField(blank=True, help_text='Original Equipment Manufacturer number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='manufacturer_part_number',
            field=models.CharField(blank=True, help_text="Manufacturer's part number (up to 40 digits)", max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='material_description',
            field=models.CharField(default=1, help_text='Short description of the material/part', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='material_description_ar',
            field=models.CharField(blank=True, help_text='Arabic description of the material/part', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='material_group',
            field=models.CharField(blank=True, help_text='Material group classification', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='material_type',
            field=models.CharField(blank=True, help_text='Type of material (FERT, HAWA, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='minimum_order_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Minimum order quantity', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='minimum_safety_stock',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Minimum safety stock quantity', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='moving_average_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Moving average price or periodic unit price', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='net_weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Net weight in kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='old_material_number',
            field=models.CharField(blank=True, help_text='Previous material number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='parts_number',
            field=models.CharField(blank=True, help_text='Unique parts identification number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='planned_delivery_time_days',
            field=models.PositiveIntegerField(blank=True, help_text='Planned delivery time in days', null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='plant',
            field=models.CharField(blank=True, help_text='Plant code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='price_unit_peinh',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Price unit (PEINH)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='safety_stock',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Safety stock quantity', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='size_dimensions',
            field=models.CharField(blank=True, help_text='Physical dimensions of the part', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='storage_location',
            field=models.CharField(blank=True, help_text='Storage location code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='valuation_class',
            field=models.CharField(blank=True, help_text='Valuation class code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='warehouse_number',
            field=models.CharField(blank=True, help_text='Warehouse identification number', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='description',
            field=models.TextField(blank=True, help_text='Legacy description field'),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(blank=True, help_text='Legacy name field', max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Selling price', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='part',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Available quantity'),
        ),
        migrations.AlterField(
            model_name='part',
            name='sku',
            field=models.CharField(blank=True, help_text='Legacy SKU field', max_length=50),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['parts_number'], name='parts_part_parts_number_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['material_description'], name='parts_part_material_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['manufacturer_part_number'], name='parts_part_mfg_part_num_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['manufacturer_oem_number'], name='parts_part_mfg_oem_num_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['material_type'], name='parts_part_material_type_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['plant'], name='parts_part_plant_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['material_group'], name='parts_part_material_group_idx'),
        ),
    ]
