# Generated by Django 5.2.4 on 2025-11-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0007_populate_parts_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='parts_number',
            field=models.CharField(blank=True, help_text='Unique parts identification number', max_length=50, null=True, unique=True),
        ),
    ]
