# Generated by Django 5.2.4 on 2025-11-02 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0002_add_vendor_field'),
        ('parts', '0008_add_parts_number_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor who supplies this part', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_parts', to='business_partners.businesspartner'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['vendor'], name='parts_part_vendor_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['vendor', 'is_active'], name='parts_part_vendor_active_idx'),
        ),
    ]
