# Generated by Django 5.2.7 on 2025-11-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0009_add_vendor_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='account_assignment_group',
            field=models.CharField(blank=True, help_text='Account assignment group for material', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='availability_check',
            field=models.CharField(blank=True, help_text='Availability check rule', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='distribution_channel',
            field=models.CharField(blank=True, help_text='Distribution channel code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='forecast_model',
            field=models.CharField(blank=True, help_text='Forecast model', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='forecast_periods',
            field=models.PositiveIntegerField(blank=True, help_text='Number of forecast periods', null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='general_item_category_group',
            field=models.CharField(blank=True, help_text='General item category group', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='historical_periods',
            field=models.PositiveIntegerField(blank=True, help_text='Number of historical periods', null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='industry_sector',
            field=models.CharField(blank=True, help_text='Industry sector code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='initialization_indicator',
            field=models.CharField(blank=True, choices=[('X', 'Initialize'), (' ', 'Do not initialize')], help_text='Initialization indicator', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='item_category_group',
            field=models.CharField(blank=True, help_text='Item category group from material master', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='loading_group',
            field=models.CharField(blank=True, help_text='Loading group', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='lot_size',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Lot size for materials planning', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='material_pricing_group',
            field=models.CharField(blank=True, help_text='Material pricing group', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='mrp_controller',
            field=models.CharField(blank=True, help_text='MRP controller (materials planner)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='mrp_group',
            field=models.CharField(blank=True, help_text='MRP group', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='mrp_type',
            field=models.CharField(blank=True, help_text='MRP type', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='period_indicator',
            field=models.CharField(blank=True, choices=[('D', 'Day'), ('W', 'Week'), ('M', 'Month'), ('Y', 'Year')], help_text='Period indicator for forecasting', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='price_control_indicator',
            field=models.CharField(blank=True, choices=[('S', 'Standard Price'), ('V', 'Moving Average Price')], help_text='Price control indicator (S/V)', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='procurement_type',
            field=models.CharField(blank=True, choices=[('F', 'In-house production'), ('E', 'External procurement'), ('B', 'Both')], help_text='Procurement type', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='profit_center',
            field=models.CharField(blank=True, help_text='Profit center code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='purchasing_group',
            field=models.CharField(blank=True, help_text='Purchasing group', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='reorder_point',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Reorder point quantity', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='sales_organization',
            field=models.CharField(blank=True, help_text='Sales organization code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='standard_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standard price', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='storage_bin',
            field=models.CharField(blank=True, help_text='Storage bin location', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='tax_classification_material',
            field=models.CharField(blank=True, help_text='Tax classification for material', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='total_replenishment_lead_time',
            field=models.PositiveIntegerField(blank=True, help_text='Total replenishment lead time in workdays', null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='transportation_group',
            field=models.CharField(blank=True, help_text='Transportation group', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='valuation_category',
            field=models.CharField(blank=True, help_text='Valuation category', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='weight_of_unit',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Weight of unit in kg', max_digits=10, null=True),
        ),
    ]
