# Generated by Django 5.2.4 on 2025-11-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0010_part_account_assignment_group_and_more'),
        ('vehicles', '0002_vehiclemake_vehiclemodeltaxonomy_partcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='vehicle_variants',
            field=models.ManyToManyField(blank=True, help_text='Compatible vehicle variants for this part', related_name='parts', to='vehicles.vehiclevariant'),
        ),
    ]
