# Generated by Django 5.2.8 on 2025-12-03 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0012_passwordhistory'),
        ('parts', '0012_order_payment_method_order_payment_status'),
        # ('vehicles', '0002_vehiclemake_vehiclemodeltaxonomy_partcategory_and_more'),  # Disabled - vehicles app not in INSTALLED_APPS
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Current status of the part listing', max_length=20),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['status'], name='parts_part_status_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['status', '-created_at'], name='parts_part_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['category', 'status'], name='parts_part_cat_status_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['brand', 'status'], name='parts_part_brand_status_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['dealer', 'status'], name='parts_part_dealer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['vendor', 'status'], name='parts_part_vendor_status_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['status', 'price'], name='parts_part_status_price_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['status', 'quantity'], name='parts_part_status_qty_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['is_featured', 'status'], name='parts_part_featured_status_idx'),
        ),
    ]
