# Generated by Django 5.2.8 on 2025-12-04 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0013_part_status_part_parts_part_status_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='vehicle_variants',
        ),
    ]
