# Generated by Django 5.2.8 on 2025-12-06 00:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0013_vendorprofile_registration_date_vendorprofile_user'),
        ('parts', '0014_remove_part_vehicle_variants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='parts_number',
            field=models.CharField(blank=True, help_text='Parts identification number', max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(fields=('parts_number', 'vendor'), name='unique_part_per_vendor'),
        ),
    ]
