# Generated by Django 5.0.1 on 2025-12-18 23:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0017_vendororderitemstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='original_currency',
            field=models.CharField(default='USD', help_text='Currency code the vendor used when setting the price (USD, SAR, GBP, etc.)', max_length=3),
        ),
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Selling price in original currency', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
