# Generated by Django 5.2.9 on 2025-12-23 07:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0018_add_original_currency_to_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wholesale price for vendor/admin use', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
