# Generated by Django 5.2.9 on 2025-12-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0019_part_wholesale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='wholesale_price',
        ),
    ]
