# Generated by Django 5.0.1 on 2026-01-03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0020_remove_part_wholesale_price'),
    ]

    operations = [
        # Add fields to Cart model
        migrations.AddField(
            model_name='cart',
            name='currency_code',
            field=models.CharField(default='USD', help_text='Currency code used for display and locking', max_length=3),
        ),
        migrations.AddField(
            model_name='cart',
            name='rate_lock_refreshed_at',
            field=models.DateTimeField(blank=True, help_text='When cart rates were last validated/refreshed', null=True),
        ),
        
        # Add fields to CartItem model
        migrations.AddField(
            model_name='cartitem',
            name='locked_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate locked at time of adding to cart (vendor_currency → USD)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='rate_lock_timestamp',
            field=models.DateTimeField(blank=True, help_text="When this item's exchange rate was locked", null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='rate_valid_until',
            field=models.DateTimeField(blank=True, help_text='Until when the locked rate is valid (15 minutes from lock)', null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='vendor_currency_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Price in vendor's original currency at time of locking", max_digits=12, null=True),
        ),
    ]