# Generated by Django 5.0.1 on 2026-01-03

from django.db import migrations, models
import django.utils.timezone
from django.core.validators import MinValueValidator
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0021_add_cart_rate_locking_fields'),
    ]

    operations = [
        # Add rate locking fields to Order model
        migrations.AddField(
            model_name='order',
            name='exchange_rate_locked_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text='When the exchange rates were locked for this order'
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='exchange_rate_valid_until',
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text='Until when the locked exchange rates are valid (24 hours from order creation)'
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='locked_base_currency_code',
            field=models.CharField(
                default='USD',
                max_length=3,
                help_text='Base currency used for rate locking (usually USD)'
            ),
        ),
        
        # Add rate locking fields to OrderItem model
        migrations.AddField(
            model_name='orderitem',
            name='locked_exchange_rate',
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text='Exchange rate locked at time of order (vendor_currency → USD)',
                max_digits=12,
                null=True,
                validators=[MinValueValidator(Decimal('0.000001'))]
            ),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='original_currency_code',
            field=models.CharField(
                default='USD',
                max_length=3,
                help_text='Original currency code of the part/vendor at time of order'
            ),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor_currency_amount',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Price in vendor\'s original currency at time of order',
                max_digits=12,
                null=True,
                validators=[MinValueValidator(Decimal('0.00'))]
            ),
        ),
    ]