# Generated by Django 5.2.9 on 2026-01-02 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0022_add_order_rate_locking_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='exchange_rate_locked_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='exchange_rate_valid_until',
        ),
        migrations.RemoveField(
            model_name='order',
            name='locked_base_currency_code',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='locked_exchange_rate',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='original_currency_code',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='vendor_currency_amount',
        ),
    ]
