# Generated by Django 5.0.1 on 2026-01-04 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0026_remove_address_city_area_and_more'),
        ('parts', '0024_city_country_alter_cityarea_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaudiCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(max_length=100)),
                ('region_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Saudi City',
                'verbose_name_plural': 'Saudi Cities',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.AlterField(
            model_name='cityarea',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='parts.saudicity'),
        ),
        migrations.AlterField(
            model_name='ordershipping',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_shipments', to='parts.saudicity'),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rates', to='parts.saudicity'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
