# Generated by Django 5.2.9 on 2026-01-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0026_city_country_alter_cityarea_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkuploadlog',
            name='processing_mode',
            field=models.CharField(choices=[('sync', 'Synchronous'), ('async_celery', 'Async (Celery)'), ('async_db', 'Async (Database Queue)')], default='async_celery', max_length=20),
        ),
        migrations.AlterField(
            model_name='bulkuploadlog',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Completed')], default='queued', max_length=20),
        ),
    ]
