# Generated by Django 5.2.9 on 2026-01-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0027_add_processing_mode_to_bulkuploadlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='locked_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate locked at time of order (vendor_currency -> USD)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='original_currency_code',
            field=models.CharField(blank=True, help_text='Currency code the vendor used when setting the price', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor_currency_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Price in vendor's original currency at time of order", max_digits=12, null=True),
        ),
    ]
