# Generated by Django 5.2.9 on 2026-01-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0028_orderitem_locked_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='reserved_stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock currently held in checkout processes'),
        ),
    ]
