# Generated by Django 5.2.9 on 2026-01-09 00:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0029_inventory_reserved_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax amount for this item', max_digits=10),
        ),
    ]
