# Generated by Trae on 2026-01-10

from django.db import migrations, connection


def fix_city_fk_constraints(apps, schema_editor):
    vendor = connection.vendor
    
    # Tables and their intended FK behavior
    targets = {
        'parts_ordershipping': {'on_delete': 'NO ACTION', 'name': 'parts_ordershipping_city_id_fk_parts_city_id'},
        'parts_cityarea': {'on_delete': 'CASCADE', 'name': 'parts_cityarea_city_id_fk_parts_city_id'},
        'parts_shippingrate': {'on_delete': 'CASCADE', 'name': 'parts_shippingrate_city_id_fk_parts_city_id'},
    }

    with connection.cursor() as cursor:
        if vendor == 'postgresql':
            # Keep existing PG logic
            cursor.execute("""
DO $$
DECLARE r record;
BEGIN
  IF to_regclass('public.parts_saudicity') IS NOT NULL THEN
    FOR r IN
      SELECT conname, conrelid::regclass::text AS table_name
      FROM pg_constraint
      WHERE contype = 'f'
        AND confrelid = 'parts_saudicity'::regclass
        AND conrelid IN (
          'parts_ordershipping'::regclass,
          'parts_cityarea'::regclass,
          'parts_shippingrate'::regclass
        )
    LOOP
      EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', r.table_name, r.conname);
    END LOOP;
  END IF;

  IF to_regclass('public.parts_city') IS NULL THEN
    RAISE EXCEPTION 'parts_city table is missing; cannot repair city foreign keys.';
  END IF;

  IF to_regclass('public.parts_ordershipping') IS NOT NULL THEN
    IF NOT EXISTS (
      SELECT 1 FROM pg_constraint
      WHERE conname = 'parts_ordershipping_city_id_fk_parts_city_id'
    ) THEN
      EXECUTE 'ALTER TABLE parts_ordershipping '
              'ADD CONSTRAINT parts_ordershipping_city_id_fk_parts_city_id '
              'FOREIGN KEY (city_id) REFERENCES parts_city(id) ON DELETE NO ACTION';
    END IF;
  END IF;

  IF to_regclass('public.parts_cityarea') IS NOT NULL THEN
    IF NOT EXISTS (
      SELECT 1 FROM pg_constraint
      WHERE conname = 'parts_cityarea_city_id_fk_parts_city_id'
    ) THEN
      EXECUTE 'ALTER TABLE parts_cityarea '
              'ADD CONSTRAINT parts_cityarea_city_id_fk_parts_city_id '
              'FOREIGN KEY (city_id) REFERENCES parts_city(id) ON DELETE CASCADE';
    END IF;
  END IF;

  IF to_regclass('public.parts_shippingrate') IS NOT NULL THEN
    IF NOT EXISTS (
      SELECT 1 FROM pg_constraint
      WHERE conname = 'parts_shippingrate_city_id_fk_parts_city_id'
    ) THEN
      EXECUTE 'ALTER TABLE parts_shippingrate '
              'ADD CONSTRAINT parts_shippingrate_city_id_fk_parts_city_id '
              'FOREIGN KEY (city_id) REFERENCES parts_city(id) ON DELETE CASCADE';
    END IF;
  END IF;
END $$;
            """)
        elif vendor in ['mysql', 'mariadb']:
            # MariaDB/MySQL logic
            
            # 1. Drop constraints pointing to parts_saudicity
            for table_name in targets.keys():
                cursor.execute(f"""
                    SELECT CONSTRAINT_NAME
                    FROM information_schema.KEY_COLUMN_USAGE
                    WHERE TABLE_NAME = '{table_name}'
                      AND TABLE_SCHEMA = DATABASE()
                      AND REFERENCED_TABLE_NAME = 'parts_saudicity'
                """)
                rows = cursor.fetchall()
                for (constraint_name,) in rows:
                    cursor.execute(f"ALTER TABLE {table_name} DROP FOREIGN KEY {constraint_name}")
            
            # 2. Check if parts_city exists
            cursor.execute("""
                SELECT COUNT(*)
                FROM information_schema.TABLES
                WHERE TABLE_NAME = 'parts_city'
                  AND TABLE_SCHEMA = DATABASE()
            """)
            if cursor.fetchone()[0] == 0:
                raise Exception('parts_city table is missing; cannot repair city foreign keys.')

            # 3. Add constraints pointing to parts_city if they don't exist
            for table_name, info in targets.items():
                # Check if constraint already exists
                cursor.execute(f"""
                    SELECT COUNT(*)
                    FROM information_schema.TABLE_CONSTRAINTS
                    WHERE CONSTRAINT_NAME = '{info['name']}'
                      AND TABLE_NAME = '{table_name}'
                      AND TABLE_SCHEMA = DATABASE()
                """)
                if cursor.fetchone()[0] == 0:
                    cursor.execute(f"""
                        ALTER TABLE {table_name}
                        ADD CONSTRAINT {info['name']}
                        FOREIGN KEY (city_id) REFERENCES parts_city(id)
                        ON DELETE {info['on_delete']}
                    """)


class Migration(migrations.Migration):
    dependencies = [
        ("parts", "0030_orderitem_tax_amount"),
    ]

    operations = [
        migrations.RunPython(fix_city_fk_constraints, reverse_code=migrations.RunPython.noop),
    ]

