# Generated by Django 5.0.1 on 2026-01-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0031_fix_city_fk_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartFieldConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('group_name', models.CharField(default='General', max_length=50)),
                ('is_locked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Part Field Configuration',
                'verbose_name_plural': 'Part Field Configurations',
                'ordering': ['group_name', 'field_name'],
            },
        ),
    ]
