# Generated by Django 5.2.9 on 2026-01-23 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0033_alter_part_warehouse_number'),
        ('vendor_employees', '0006_vendoremployee_locations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='plant',
            field=models.ForeignKey(blank=True, help_text='Plant (Vendor Location)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='vendor_employees.vendorlocation'),
        ),
    ]
