# Generated by Django 5.2.9 on 2026-01-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0034_alter_part_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='plant',
            field=models.CharField(blank=True, help_text='Plant code', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='warehouse_number',
            field=models.CharField(blank=True, help_text='Warehouse identification number', max_length=10, null=True),
        ),
    ]
