# Generated by Django 5.2.9 on 2026-01-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0035_alter_part_plant_alter_part_warehouse_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='plant',
            field=models.CharField(blank=True, help_text='Plant code', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='storage_location',
            field=models.CharField(blank=True, help_text='Storage location code', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='warehouse_number',
            field=models.CharField(blank=True, help_text='Warehouse identification number', max_length=100, null=True),
        ),
    ]
