# Generated by Django 5.2.7 on 2025-11-02 11:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Make name in English', max_length=100, unique=True)),
                ('name_arabic', models.CharField(blank=True, help_text='Make name in Arabic', max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vehicle_taxonomy/makes/logos/')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle Make',
                'verbose_name_plural': 'Vehicle Makes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModelTaxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Model name', max_length=100)),
                ('model_code', models.CharField(blank=True, help_text='Internal model code', max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_models', to='vehicles.vehiclemake')),
            ],
            options={
                'verbose_name': 'Vehicle Model (Taxonomy)',
                'verbose_name_plural': 'Vehicle Models (Taxonomy)',
                'ordering': ['make__name', 'name'],
                'unique_together': {('make', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name in English', max_length=100)),
                ('name_arabic', models.CharField(blank=True, help_text='Category name in Arabic', max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class name', max_length=50, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Sort order within parent category')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for hierarchical structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='vehicles.partcategory')),
            ],
            options={
                'verbose_name': 'Part Category',
                'verbose_name_plural': 'Part Categories',
                'ordering': ['parent__name', 'sort_order', 'name'],
                'unique_together': {('parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VehicleVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Variant name (e.g., 'LX', 'EX', 'Sport')", max_length=100)),
                ('year', models.PositiveIntegerField(help_text='Model year', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2050)])),
                ('engine_code', models.CharField(blank=True, help_text="Engine code (e.g., 'K20A')", max_length=50, null=True)),
                ('transmission_type', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('cvt', 'CVT'), ('dct', 'Dual Clutch'), ('amt', 'AMT')], help_text='Transmission type', max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric'), ('cng', 'CNG'), ('lpg', 'LPG')], help_text='Fuel type', max_length=20)),
                ('engine_displacement', models.DecimalField(blank=True, decimal_places=1, help_text='Engine displacement in liters', max_digits=4, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='vehicles.vehiclemodeltaxonomy')),
            ],
            options={
                'verbose_name': 'Vehicle Variant',
                'verbose_name_plural': 'Vehicle Variants',
                'ordering': ['model__make__name', 'model__name', '-year', 'name'],
                'unique_together': {('model', 'name', 'year', 'engine_code')},
            },
        ),
    ]
