# Generated by Django 5.2.9 on 2026-01-20 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vendoremployee',
            new_name='vendor_empl_vendor__735366_idx',
            old_name='vendor_employees_vendor_i_6f4ef4_idx',
        ),
        migrations.RenameIndex(
            model_name='vendoremployee',
            new_name='vendor_empl_user_id_b5bf90_idx',
            old_name='vendor_employees_user_i_6ba5d8_idx',
        ),
        migrations.RenameIndex(
            model_name='vendorpagepermission',
            new_name='vendor_empl_vendor__be10fe_idx',
            old_name='vendor_employees_vendor_i_d1f35b_idx',
        ),
        migrations.RenameIndex(
            model_name='vendorpagepermission',
            new_name='vendor_empl_code_0c43d8_idx',
            old_name='vendor_employees_code_i_4a0f3d_idx',
        ),
        migrations.RenameIndex(
            model_name='vendorrole',
            new_name='vendor_empl_vendor__10590d_idx',
            old_name='vendor_employees_vendor_i_109c63_idx',
        ),
        migrations.RenameIndex(
            model_name='vendorrolepermission',
            new_name='vendor_empl_role_id_39f00e_idx',
            old_name='vendor_employees_role_i_3c2a88_idx',
        ),
    ]
