# Generated by Django 5.2.9 on 2026-01-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_employees', '0002_rename_vendor_employees_vendor_i_6f4ef4_idx_vendor_empl_vendor__735366_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorrolepermission',
            name='can_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorrolepermission',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorrolepermission',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorrolepermission',
            name='can_view',
            field=models.BooleanField(default=False),
        ),
    ]
