# Generated by Django 5.2.9 on 2026-01-21 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0027_vendorprofile_bank_account_holder_name_and_more'),
        ('vendor_employees', '0003_vendorrolepermission_can_create_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='business_partners.businesspartner')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('vendor', 'name')},
            },
        ),
        migrations.AddField(
            model_name='vendoremployee',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='vendor_employees.vendorlocation'),
        ),
    ]
