# Generated by Django 5.2.9 on 2026-01-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_employees', '0004_vendorlocation_vendoremployee_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoremployee',
            name='invitation_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
