# Generated by Django 5.0.1 on 2026-01-23 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_employees', '0005_vendoremployee_invitation_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoremployee',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='employees', to='vendor_employees.vendorlocation'),
        ),
        migrations.AlterField(
            model_name='vendoremployee',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_legacy', to='vendor_employees.vendorlocation'),
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to='vendor_employees.vendorlocation')),
            ],
            options={
                'ordering': ['plant', 'name'],
                'unique_together': {('plant', 'name')},
            },
        ),
    ]
