# Generated by Django 5.2.9 on 2026-01-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_employees', '0007_warehouse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
