# Generated by Django 5.2.7 on 2025-11-02 10:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp_number', models.CharField(help_text='Unique business partner number', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Business partner name', max_length=255)),
                ('type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('organization', 'Organization')], default='company', max_length=20)),
                ('legal_identifier', models.CharField(blank=True, help_text='Tax ID, Registration number, etc.', max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending Approval')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_business_partners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Partner',
                'verbose_name_plural': 'Business Partners',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('billing', 'Billing Address'), ('shipping', 'Shipping Address'), ('office', 'Office Address'), ('warehouse', 'Warehouse Address')], max_length=20)),
                ('street', models.TextField(help_text='Street address')),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='business_partners.businesspartner')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('mobile', 'Mobile'), ('fax', 'Fax'), ('website', 'Website')], max_length=20)),
                ('value', models.CharField(help_text='Contact value (email, phone, etc.)', max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='business_partners.businesspartner')),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credit limit for the customer', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('loyalty_tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], default='bronze', max_length=20)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default discount percentage for the customer', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('preferred_currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='business_partners.businesspartner')),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
            },
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_terms', models.CharField(choices=[('net_15', 'Net 15 days'), ('net_30', 'Net 30 days'), ('net_45', 'Net 45 days'), ('net_60', 'Net 60 days'), ('cod', 'Cash on Delivery'), ('prepaid', 'Prepaid')], default='net_30', max_length=20)),
                ('bank_account_details', models.TextField(blank=True, help_text='Bank account information for payments', null=True)),
                ('vendor_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Vendor rating from 0.00 to 5.00', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to='business_partners.businesspartner')),
            ],
            options={
                'verbose_name': 'Vendor Profile',
                'verbose_name_plural': 'Vendor Profiles',
            },
        ),
        migrations.CreateModel(
            name='BusinessPartnerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('prospect', 'Prospect')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='business_partners.businesspartner')),
            ],
            options={
                'verbose_name': 'Business Partner Role',
                'verbose_name_plural': 'Business Partner Roles',
                'unique_together': {('business_partner', 'role_type')},
            },
        ),
    ]
