# Generated by Django 5.2.4 on 2025-11-02 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(blank=True, help_text='Unique application identifier', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('business_details_completed', 'Business Details Completed'), ('contact_info_completed', 'Contact Information Completed'), ('bank_details_completed', 'Bank Details Completed'), ('submitted', 'Submitted for Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requires_changes', 'Requires Changes')], default='draft', max_length=30)),
                ('current_step', models.PositiveSmallIntegerField(default=1, help_text='Current step in the registration process (1-4)')),
                ('company_name', models.CharField(blank=True, help_text='Legal company name', max_length=255, null=True)),
                ('business_type', models.CharField(blank=True, choices=[('sole_proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('llc', 'Limited Liability Company (LLC)'), ('corporation', 'Corporation'), ('cooperative', 'Cooperative'), ('other', 'Other')], max_length=30, null=True)),
                ('commercial_registration_number', models.CharField(blank=True, help_text='Commercial Registration (CR) number', max_length=50, null=True)),
                ('cr_document', models.FileField(blank=True, help_text='Commercial Registration document', null=True, upload_to='vendor_applications/cr_documents/')),
                ('legal_identifier', models.CharField(blank=True, help_text='Tax ID, VAT number, or other legal identifier', max_length=100, null=True)),
                ('business_license', models.FileField(blank=True, help_text='Business license document', null=True, upload_to='vendor_applications/business_licenses/')),
                ('establishment_date', models.DateField(blank=True, help_text='Date of business establishment', null=True)),
                ('business_description', models.TextField(blank=True, help_text='Description of business activities', null=True)),
                ('contact_person_name', models.CharField(blank=True, help_text='Primary contact person name', max_length=200, null=True)),
                ('contact_person_title', models.CharField(blank=True, help_text='Contact person job title', max_length=100, null=True)),
                ('business_phone', models.CharField(blank=True, help_text='Business phone number', max_length=20, null=True)),
                ('business_email', models.EmailField(blank=True, help_text='Business email address', max_length=254, null=True)),
                ('website', models.URLField(blank=True, help_text='Company website', null=True)),
                ('street_address', models.CharField(blank=True, help_text='Street address', max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state_province', models.CharField(blank=True, help_text='State or Province', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, help_text='Name of the bank', max_length=200, null=True)),
                ('bank_branch', models.CharField(blank=True, help_text='Bank branch name', max_length=200, null=True)),
                ('account_holder_name', models.CharField(blank=True, help_text='Account holder name (must match business name)', max_length=200, null=True)),
                ('account_number', models.CharField(blank=True, help_text='Bank account number', max_length=50, null=True)),
                ('iban', models.CharField(blank=True, help_text='International Bank Account Number (IBAN)', max_length=34, null=True)),
                ('swift_code', models.CharField(blank=True, help_text='SWIFT/BIC code', max_length=11, null=True)),
                ('bank_statement', models.FileField(blank=True, help_text='Recent bank statement for verification', null=True, upload_to='vendor_applications/bank_statements/')),
                ('expected_monthly_volume', models.DecimalField(blank=True, decimal_places=2, help_text='Expected monthly sales volume', max_digits=15, null=True)),
                ('product_categories', models.TextField(blank=True, help_text='Types of automotive parts you plan to sell', null=True)),
                ('years_in_business', models.PositiveIntegerField(blank=True, help_text='Number of years in automotive parts business', null=True)),
                ('references', models.TextField(blank=True, help_text='Business references or previous partnerships', null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Admin notes during review process', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the application was submitted for review', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the application was reviewed', null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the application was approved', null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed the application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vendor_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User applying for vendor status', on_delete=django.db.models.deletion.CASCADE, related_name='vendor_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Application',
                'verbose_name_plural': 'Vendor Applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='bp_vendor_app_status_idx'), models.Index(fields=['user'], name='bp_vendor_app_user_idx'), models.Index(fields=['application_id'], name='bp_vendor_app_id_idx'), models.Index(fields=['created_at'], name='bp_vendor_app_created_idx')],
            },
        ),
    ]
