# Generated by Django 5.2.7 on 2025-11-02 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0002_add_vendor_field'),
        ('parts', '0009_add_vendor_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReorderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('ordered', 'Ordered'), ('completed', 'Completed'), ('dismissed', 'Dismissed')], default='pending', max_length=15)),
                ('current_stock', models.PositiveIntegerField()),
                ('safety_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('reorder_level', models.PositiveIntegerField(default=10)),
                ('suggested_quantity', models.PositiveIntegerField()),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('order_placed_at', models.DateTimeField(blank=True, null=True)),
                ('order_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_reorder_notifications', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_notifications', to='parts.part')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_notifications', to='business_partners.businesspartner')),
            ],
            options={
                'verbose_name': 'Reorder Notification',
                'verbose_name_plural': 'Reorder Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'status', '-created_at'], name='business_pa_vendor__22469d_idx'), models.Index(fields=['part', 'status'], name='business_pa_part_id_bf0fa4_idx'), models.Index(fields=['priority', '-created_at'], name='business_pa_priorit_fcfd40_idx')],
            },
        ),
    ]
