# Generated by Django 5.2.7 on 2025-11-02 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0003_reordernotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User associated with this business partner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_partners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this business partner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_business_partners', to=settings.AUTH_USER_MODEL),
        ),
    ]
