# Generated by Django 5.2.7 on 2025-11-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0004_businesspartner_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the name', max_length=255),
        ),
    ]
