# Generated by Django 5.2.7 on 2025-11-02 15:32

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Populate slug fields for existing BusinessPartner records"""
    BusinessPartner = apps.get_model('business_partners', 'BusinessPartner')
    
    for bp in BusinessPartner.objects.all():
        if not bp.slug:
            base_slug = slugify(bp.name)
            slug = base_slug
            counter = 1
            
            # Ensure unique slug
            while BusinessPartner.objects.filter(slug=slug).exclude(pk=bp.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            
            bp.slug = slug
            bp.save()


def reverse_populate_slugs(apps, schema_editor):
    """Reverse migration - clear slug fields"""
    BusinessPartner = apps.get_model('business_partners', 'BusinessPartner')
    BusinessPartner.objects.update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0005_businesspartner_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
    ]
