# Generated by Django 5.2.4 on 2025-11-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0007_alter_businesspartner_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether the vendor profile is approved for platform access'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Whether two-factor authentication is enabled for this vendor'),
        ),
    ]
