# Generated by Django 5.2.4 on 2025-11-09 11:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0008_vendorprofile_is_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('required', models.BooleanField(default=False)),
                ('allowed_extensions', models.CharField(default='pdf,jpg,jpeg,png,doc,docx', help_text='Comma-separated list of allowed file extensions (e.g., pdf,jpg,png)', max_length=200)),
                ('max_file_size', models.PositiveIntegerField(default=10, help_text='Maximum file size in MB')),
                ('expiry_required', models.BooleanField(default=False, help_text='Whether documents in this category require expiry dates')),
                ('verification_required', models.BooleanField(default=False, help_text='Whether documents in this category require manual verification')),
            ],
            options={
                'verbose_name': 'Document Category',
                'verbose_name_plural': 'Document Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='vendor_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])])),
                ('file_size', models.PositiveIntegerField(editable=False)),
                ('file_hash', models.CharField(editable=False, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('needs_renewal', 'Needs Renewal')], default='pending', max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_partner', models.ForeignKey(blank=True, help_text='Associated business partner (for approved vendors)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_documents', to='business_partners.businesspartner')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_documents', to='business_partners.documentcategory')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_vendor_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_vendor_documents', to=settings.AUTH_USER_MODEL)),
                ('vendor_application', models.ForeignKey(blank=True, help_text='Associated vendor application (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='business_partners.vendorapplication')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_vendor_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Document',
                'verbose_name_plural': 'Vendor Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVerificationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_document_verifications', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_queue', to='business_partners.vendordocument')),
            ],
            options={
                'verbose_name': 'Document Verification Queue',
                'verbose_name_plural': 'Document Verification Queues',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('uploaded', 'Document Uploaded'), ('viewed', 'Document Viewed'), ('downloaded', 'Document Downloaded'), ('verified', 'Document Verified'), ('rejected', 'Document Rejected'), ('expired', 'Document Expired'), ('renewed', 'Document Renewed'), ('deleted', 'Document Deleted'), ('assigned', 'Verification Assigned'), ('unassigned', 'Verification Unassigned')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='business_partners.vendordocument')),
            ],
            options={
                'verbose_name': 'Document Audit Log',
                'verbose_name_plural': 'Document Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vendordocument',
            index=models.Index(fields=['business_partner', 'category', 'status'], name='business_pa_busines_c4c782_idx'),
        ),
        migrations.AddIndex(
            model_name='vendordocument',
            index=models.Index(fields=['vendor_application', 'status'], name='business_pa_vendor__f9df18_idx'),
        ),
        migrations.AddIndex(
            model_name='vendordocument',
            index=models.Index(fields=['status', 'expiry_date'], name='business_pa_status_a6a83f_idx'),
        ),
        migrations.AddIndex(
            model_name='vendordocument',
            index=models.Index(fields=['uploaded_at'], name='business_pa_uploade_bd8ce9_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendordocument',
            constraint=models.CheckConstraint(condition=models.Q(('vendor_application__isnull', False), ('business_partner__isnull', False), _connector='OR'), name='vendor_document_must_have_application_or_partner'),
        ),
        migrations.AddIndex(
            model_name='documentverificationqueue',
            index=models.Index(fields=['priority', 'created_at'], name='business_pa_priorit_990c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentverificationqueue',
            index=models.Index(fields=['assigned_to', 'completed_at'], name='business_pa_assigne_df373a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentauditlog',
            index=models.Index(fields=['document', 'action', '-created_at'], name='business_pa_documen_08b0af_idx'),
        ),
        migrations.AddIndex(
            model_name='documentauditlog',
            index=models.Index(fields=['performed_by', '-created_at'], name='business_pa_perform_a90d38_idx'),
        ),
        migrations.AddIndex(
            model_name='documentauditlog',
            index=models.Index(fields=['created_at'], name='business_pa_created_6bcf92_idx'),
        ),
    ]
