# Generated by Django 5.2.4 on 2025-11-09 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0009_documentcategory_vendordocument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorapplication',
            name='session_key',
            field=models.CharField(blank=True, help_text='Session key for anonymous applications', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='vendorapplication',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User applying for vendor status', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='vendorapplication',
            index=models.Index(fields=['session_key'], name='bp_vendor_app_session_idx'),
        ),
    ]
