# Generated by Django 5.2.4 on 2025-11-18 01:10

import business_partners.session_utils
import business_partners.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0010_vendorapplication_session_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='two_factor_secret',
            field=models.CharField(blank=True, help_text='Secret key for TOTP two-factor authentication', max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='VendorWorkflowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('pending', 'Pending Initial Review'), ('under_review', 'Under Administrative Review'), ('requires_info', 'Requires Additional Information'), ('approved', 'Application Approved'), ('rejected', 'Application Rejected'), ('active', 'Active Vendor'), ('suspended', 'Suspended by Admin'), ('on_probation', 'On Performance Probation'), ('terminated', 'Contract Terminated'), ('voluntarily_inactive', 'Voluntarily Inactive')], default='pending', max_length=30)),
                ('previous_status', models.CharField(blank=True, choices=[('pending', 'Pending Initial Review'), ('under_review', 'Under Administrative Review'), ('requires_info', 'Requires Additional Information'), ('approved', 'Application Approved'), ('rejected', 'Application Rejected'), ('active', 'Active Vendor'), ('suspended', 'Suspended by Admin'), ('on_probation', 'On Performance Probation'), ('terminated', 'Contract Terminated'), ('voluntarily_inactive', 'Voluntarily Inactive')], max_length=30, null=True)),
                ('escalation_level', models.PositiveSmallIntegerField(default=0, help_text='Escalation level for borderline cases')),
                ('escalation_reason', models.TextField(blank=True, help_text='Reason for escalation', null=True)),
                ('performance_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Performance score (0-100)', max_digits=5)),
                ('compliance_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Compliance score (0-100)', max_digits=5)),
                ('status_changed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('escalated_to', models.ForeignKey(blank=True, help_text='User who is handling escalated case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_vendor_reviews', to=settings.AUTH_USER_MODEL)),
                ('vendor_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_state', to='business_partners.vendorapplication')),
            ],
            options={
                'verbose_name': 'Vendor Workflow State',
                'verbose_name_plural': 'Vendor Workflow States',
            },
        ),
        migrations.CreateModel(
            name='VendorWorkflowAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30, null=True)),
                ('to_status', models.CharField(blank=True, max_length=30, null=True)),
                ('action_type', models.CharField(choices=[('status_change', 'Status Change'), ('escalation', 'Case Escalation'), ('review', 'Review Action'), ('compliance_check', 'Compliance Check'), ('performance_update', 'Performance Update')], default='status_change', max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_workflow_actions', to=settings.AUTH_USER_MODEL)),
                ('workflow_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='business_partners.vendorworkflowstate')),
            ],
            options={
                'verbose_name': 'Vendor Workflow Audit Log',
                'verbose_name_plural': 'Vendor Workflow Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorPriorityQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_type', models.CharField(choices=[('new_application', 'New Application'), ('escalated_review', 'Escalated Review'), ('compliance_issue', 'Compliance Issue'), ('performance_review', 'Performance Review'), ('renewal_required', 'Renewal Required')], max_length=20)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical'), (5, 'Urgent')], default=3)),
                ('flag_reason', models.TextField(help_text='Reason for flagging this application')),
                ('auto_flagged', models.BooleanField(default=True, help_text='Whether this was auto-flagged by the system')),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vendor_reviews', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_vendor_reviews', to=settings.AUTH_USER_MODEL)),
                ('workflow_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_queue_entries', to='business_partners.vendorworkflowstate')),
            ],
            options={
                'verbose_name': 'Vendor Priority Queue',
                'verbose_name_plural': 'Vendor Priority Queues',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('document_verification', 'Document Verification'), ('business_license', 'Business License Validation'), ('tax_id_verification', 'Tax ID Verification'), ('bank_account_validation', 'Bank Account Validation'), ('reference_check', 'Reference Check'), ('performance_review', 'Performance Review'), ('policy_compliance', 'Policy Compliance')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_passed', models.BooleanField(default=False)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('details', models.JSONField(default=dict, help_text='Detailed check results and findings')),
                ('manually_overridden', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_compliance_checks', to=settings.AUTH_USER_MODEL)),
                ('workflow_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to='business_partners.vendorworkflowstate')),
            ],
            options={
                'verbose_name': 'Vendor Compliance Check',
                'verbose_name_plural': 'Vendor Compliance Checks',
            },
        ),
        migrations.CreateModel(
            name='SecureVendorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(blank=True, help_text='Unique application identifier', max_length=20, unique=True)),
                ('session_hash', models.CharField(blank=True, help_text='SHA256 hash of session key', max_length=64, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('business_details_completed', 'Business Details Completed'), ('contact_info_completed', 'Contact Information Completed'), ('bank_details_completed', 'Bank Details Completed'), ('submitted', 'Submitted for Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requires_changes', 'Requires Changes')], default='draft', max_length=30)),
                ('current_step', models.PositiveSmallIntegerField(default=1, help_text='Current step in the registration process (1-4)')),
                ('company_name', models.CharField(blank=True, help_text='Legal company name', max_length=255, null=True)),
                ('business_type', models.CharField(blank=True, choices=[('sole_proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('llc', 'Limited Liability Company (LLC)'), ('corporation', 'Corporation'), ('cooperative', 'Cooperative'), ('other', 'Other')], max_length=30, null=True)),
                ('commercial_registration_number', models.CharField(blank=True, help_text='Commercial Registration (CR) number', max_length=50, null=True)),
                ('cr_document', models.FileField(blank=True, help_text='Commercial Registration document (PDF, JPG, PNG only, max 10MB)', null=True, upload_to='vendor_applications/cr_documents/%Y/%m/', validators=[business_partners.validators.validate_uploaded_document])),
                ('cr_document_hash', models.CharField(blank=True, help_text='SHA256 hash of CR document', max_length=64)),
                ('legal_identifier', models.CharField(blank=True, help_text='Tax ID, VAT number, or other legal identifier', max_length=100, null=True)),
                ('business_license', models.FileField(blank=True, help_text='Business license document (PDF, JPG, PNG only, max 10MB)', null=True, upload_to='vendor_applications/business_licenses/%Y/%m/', validators=[business_partners.validators.validate_uploaded_document])),
                ('business_license_hash', models.CharField(blank=True, help_text='SHA256 hash of business license', max_length=64)),
                ('establishment_date', models.DateField(blank=True, help_text='Date of business establishment', null=True)),
                ('business_description', models.TextField(blank=True, help_text='Description of business activities', null=True)),
                ('contact_person_name', models.CharField(blank=True, help_text='Primary contact person name', max_length=200, null=True)),
                ('contact_person_title', models.CharField(blank=True, help_text='Contact person job title', max_length=100, null=True)),
                ('business_phone', models.CharField(blank=True, help_text='Business phone number', max_length=20, null=True)),
                ('business_email', models.EmailField(blank=True, help_text='Business email address', max_length=254, null=True)),
                ('website', models.URLField(blank=True, help_text='Company website', null=True)),
                ('street_address', models.CharField(blank=True, help_text='Street address', max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state_province', models.CharField(blank=True, help_text='State or Province', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, help_text='Name of the bank', max_length=200, null=True)),
                ('bank_branch', models.CharField(blank=True, help_text='Bank branch name', max_length=200, null=True)),
                ('account_holder_name', models.CharField(blank=True, help_text='Account holder name (must match business name)', max_length=200, null=True)),
                ('account_number', models.CharField(blank=True, help_text='Bank account number', max_length=50, null=True)),
                ('iban', models.CharField(blank=True, help_text='International Bank Account Number (IBAN)', max_length=34, null=True)),
                ('swift_code', models.CharField(blank=True, help_text='SWIFT/BIC code', max_length=11, null=True)),
                ('bank_statement', models.FileField(blank=True, help_text='Recent bank statement (PDF, JPG, PNG only, max 10MB)', null=True, upload_to='vendor_applications/bank_statements/%Y/%m/', validators=[business_partners.validators.validate_uploaded_document])),
                ('bank_statement_hash', models.CharField(blank=True, help_text='SHA256 hash of bank statement', max_length=64)),
                ('expected_monthly_volume', models.DecimalField(blank=True, decimal_places=2, help_text='Expected monthly sales volume', max_digits=15, null=True)),
                ('product_categories', models.TextField(blank=True, help_text='Types of automotive parts you plan to sell', null=True)),
                ('years_in_business', models.PositiveIntegerField(blank=True, help_text='Number of years in automotive parts business', null=True)),
                ('references', models.TextField(blank=True, help_text='Business references or previous partnerships', null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Admin notes during review process', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the application was submitted for review', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the application was reviewed', null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the application was approved', null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed the application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_secure_vendor_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User applying for vendor status', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secure_vendor_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Secure Vendor Application',
                'verbose_name_plural': 'Secure Vendor Applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='bp_secure_vendor_status_idx'), models.Index(fields=['user'], name='bp_secure_vendor_user_idx'), models.Index(fields=['session_hash'], name='bp_secure_vendor_session_idx'), models.Index(fields=['application_id'], name='bp_secure_vendor_appid_idx'), models.Index(fields=['created_at'], name='bp_secure_vendor_created_idx')],
            },
            bases=(business_partners.session_utils.SecureSessionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='VendorAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('bank_details_updated', 'Bank Details Updated'), ('bank_details_accessed', 'Bank Details Accessed'), ('file_uploaded', 'File Uploaded'), ('security_suspicious_activity', 'Suspicious Activity'), ('security_rate_limit_exceeded', 'Rate Limit Exceeded'), ('security_invalid_file_upload', 'Invalid File Upload'), ('security_password_changed', 'Password Changed'), ('security_2fa_enabled', '2FA Enabled'), ('security_2fa_disabled', '2FA Disabled'), ('security_2fa_verification_failed', '2FA Verification Failed')], max_length=50)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the action')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who performed the action', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, limit_choices_to={'type': 'vendor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='business_partners.businesspartner')),
            ],
            options={
                'verbose_name': 'Vendor Audit Log',
                'verbose_name_plural': 'Vendor Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', '-created_at'], name='business_pa_vendor__b19cca_idx'), models.Index(fields=['user', '-created_at'], name='business_pa_user_id_13f4fb_idx'), models.Index(fields=['action_type', '-created_at'], name='business_pa_action__425e10_idx'), models.Index(fields=['severity', '-created_at'], name='business_pa_severit_1a32fe_idx'), models.Index(fields=['ip_address', '-created_at'], name='business_pa_ip_addr_099683_idx')],
            },
        ),
        migrations.CreateModel(
            name='VendorPerformanceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('completed_orders', models.PositiveIntegerField(default=0)),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('quality_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('performance_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(limit_choices_to={'type': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='performance_scores', to='business_partners.businesspartner')),
            ],
            options={
                'verbose_name': 'Vendor Performance Score',
                'verbose_name_plural': 'Vendor Performance Scores',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', '-created_at'], name='business_pa_vendor__a801ca_idx'), models.Index(fields=['vendor', 'period_start', 'period_end'], name='business_pa_vendor__a142e0_idx'), models.Index(fields=['performance_score', '-created_at'], name='business_pa_perform_2895a9_idx')],
                'unique_together': {('vendor', 'period_start', 'period_end')},
            },
        ),
        migrations.AddIndex(
            model_name='vendorworkflowstate',
            index=models.Index(fields=['current_status', 'escalation_level'], name='business_pa_current_f78598_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorworkflowstate',
            index=models.Index(fields=['performance_score', 'compliance_score'], name='business_pa_perform_3832be_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorworkflowauditlog',
            index=models.Index(fields=['workflow_state', 'created_at'], name='business_pa_workflo_9d5771_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorworkflowauditlog',
            index=models.Index(fields=['performed_by', 'created_at'], name='business_pa_perform_166948_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorpriorityqueue',
            index=models.Index(fields=['queue_type', 'priority', 'is_resolved'], name='business_pa_queue_t_ba7ef1_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorpriorityqueue',
            index=models.Index(fields=['assigned_to', 'is_resolved'], name='business_pa_assigne_69b04c_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorcompliancecheck',
            index=models.Index(fields=['workflow_state', 'check_type'], name='business_pa_workflo_5606fc_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorcompliancecheck',
            index=models.Index(fields=['is_passed', 'priority'], name='business_pa_is_pass_576620_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorcompliancecheck',
            unique_together={('workflow_state', 'check_type')},
        ),
    ]
