# Generated by Django 5.2.8 on 2025-12-04 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0012_passwordhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='registration_date',
            field=models.DateField(blank=True, help_text='Date when the vendor was registered on the platform', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User account associated with this vendor profile', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
