# Generated by Django 5.2.8 on 2025-12-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0013_vendorprofile_registration_date_vendorprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='description',
            field=models.TextField(blank=True, help_text='Business description', null=True),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='logo',
            field=models.ImageField(blank=True, help_text='Business logo', null=True, upload_to='vendor_logos/'),
        ),
    ]
