# Generated by Django 5.0.1 on 2025-12-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0014_businesspartner_description_businesspartner_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_statement',
            field=models.FileField(blank=True, help_text='Recent bank statement', null=True, upload_to='vendor_documents/bank_statements/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='business_license',
            field=models.FileField(blank=True, help_text='Business license document', null=True, upload_to='vendor_documents/business_licenses/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='business_structure',
            field=models.CharField(blank=True, choices=[('sole_proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('llc', 'Limited Liability Company (LLC)'), ('corporation', 'Corporation'), ('cooperative', 'Cooperative'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='contact_person_name',
            field=models.CharField(blank=True, help_text='Primary contact person name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='contact_person_title',
            field=models.CharField(blank=True, help_text='Contact person job title', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='cr_document',
            field=models.FileField(blank=True, help_text='Commercial Registration document', null=True, upload_to='vendor_documents/cr_documents/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='establishment_date',
            field=models.DateField(blank=True, help_text='Date of business establishment', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='expected_monthly_volume',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected monthly sales volume', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='product_categories',
            field=models.TextField(blank=True, help_text='Types of automotive parts you sell', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='references',
            field=models.TextField(blank=True, help_text='Business references or previous partnerships', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='swift_code',
            field=models.CharField(blank=True, help_text='SWIFT/BIC code', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='years_in_business',
            field=models.PositiveIntegerField(blank=True, help_text='Number of years in automotive parts business', null=True),
        ),
    ]
