# Generated by Django 5.0.1 on 2025-12-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0015_vendorprofile_bank_statement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='commercial_invoice_sample',
            field=models.FileField(blank=True, help_text='Sample commercial invoice', null=True, upload_to='vendor_documents/commercial_invoices/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='company_profile',
            field=models.FileField(blank=True, help_text='Company profile or brochure', null=True, upload_to='vendor_documents/company_profiles/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='import_export_license',
            field=models.FileField(blank=True, help_text='Import/export license (if applicable)', null=True, upload_to='vendor_documents/import_export_licenses/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='insurance_certificate',
            field=models.FileField(blank=True, help_text='Business insurance certificate', null=True, upload_to='vendor_documents/insurance_certificates/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='quality_certificate',
            field=models.FileField(blank=True, help_text='ISO or quality management certificate', null=True, upload_to='vendor_documents/quality_certificates/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='supplier_certification',
            field=models.FileField(blank=True, help_text='Manufacturer authorization or supplier certification', null=True, upload_to='vendor_documents/supplier_certifications/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='tax_certificate',
            field=models.FileField(blank=True, help_text='Tax registration certificate', null=True, upload_to='vendor_documents/tax_certificates/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='vat_certificate',
            field=models.FileField(blank=True, help_text='VAT registration certificate', null=True, upload_to='vendor_documents/vat_certificates/'),
        ),
    ]
