# Generated by Django 5.2.9 on 2025-12-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0017_remove_vendorprofile_tax_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securevendorapplication',
            name='application_reference',
        ),
        migrations.RemoveField(
            model_name='securevendorapplication',
            name='encrypted_data',
        ),
        migrations.RemoveField(
            model_name='securevendorapplication',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='securevendorapplication',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='securevendorapplication',
            name='vendor_profile',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='backup_codes',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='bank_routing_number',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='tax_number',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='vendor_code',
        ),
        migrations.AlterField(
            model_name='securevendorapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('business_details_completed', 'Business Details Completed'), ('contact_info_completed', 'Contact Information Completed'), ('bank_details_completed', 'Bank Details Completed'), ('submitted', 'Submitted for Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requires_changes', 'Requires Changes')], default='draft', max_length=30),
        ),
    ]

