# Generated by Django 5.2.9 on 2025-12-24 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0018_remove_securevendorapplication_application_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securevendorapplication',
            name='application_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='securevendorapplication',
            name='encrypted_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='securevendorapplication',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securevendorapplication',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securevendorapplication',
            name='vendor_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secure_vendor_applications', to='business_partners.vendorprofile'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='backup_codes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_routing_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='securevendorapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('draft', 'Draft'), ('business_details_completed', 'Business Details Completed'), ('contact_info_completed', 'Contact Information Completed'), ('bank_details_completed', 'Bank Details Completed'), ('submitted', 'Submitted for Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requires_changes', 'Requires Changes')], default='draft', max_length=30),
        ),
    ]

