# Generated by Django 5.0.1 on 2025-12-24 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0019_restore_vendorprofile_and_securevendorapplication_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(help_text='Part number / SKU', max_length=100)),
                ('description', models.TextField(help_text='Parts description')),
                ('make', models.CharField(help_text='Vehicle make (e.g., Toyota, Honda)', max_length=100)),
                ('model', models.CharField(help_text='Vehicle model (e.g., Camry, Civic)', max_length=100)),
                ('year', models.PositiveIntegerField(help_text='Vehicle year')),
                ('trim', models.CharField(blank=True, help_text='Vehicle trim (optional)', max_length=100, null=True)),
                ('engine', models.CharField(blank=True, help_text='Engine specification (optional)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(help_text='Vendor who owns this catalog item', on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='business_partners.businesspartner')),
            ],
            options={
                'verbose_name': 'Catalog Item',
                'verbose_name_plural': 'Catalog Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Catalog item image', upload_to='catalog_images/')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary display image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalog_item', models.ForeignKey(help_text='Parent catalog item', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='business_partners.catalogitem')),
            ],
            options={
                'verbose_name': 'Catalog Item Image',
                'verbose_name_plural': 'Catalog Item Images',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
    ]
