# Generated by Django 5.2.4 on 2025-12-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0020_remove_part_wholesale_price'),
        ('business_partners', '0020_catalog_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='category',
            field=models.ForeignKey(
                blank=True,
                help_text='Category for this catalog item',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='vendor_catalog_items',
                to='parts.category',
            ),
        ),
    ]

