# Generated by Django 5.2.4 on 2025-12-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0021_catalogitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='model',
            field=models.CharField(
                blank=True,
                help_text='Vehicle model (e.g., Camry, Civic)',
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='year',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Vehicle year',
                null=True,
            ),
        ),
    ]

