# Generated by Django 5.2.9 on 2025-12-30 21:13

from django.db import migrations, models


def drop_vendorprofile_tax_certificate_column(apps, schema_editor):
    table_name = 'business_partners_vendorprofile'
    column_name = 'tax_certificate'

    try:
        table_names = schema_editor.connection.introspection.table_names()
    except Exception:
        return

    if table_name not in table_names:
        return

    try:
        with schema_editor.connection.cursor() as cursor:
            columns = [
                c.name
                for c in schema_editor.connection.introspection.get_table_description(
                    cursor, table_name
                )
            ]
    except Exception:
        return

    if column_name not in columns:
        return

    qn = schema_editor.quote_name
    schema_editor.execute(
        f'ALTER TABLE {qn(table_name)} DROP COLUMN {qn(column_name)}'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0022_catalogitem_optional_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    drop_vendorprofile_tax_certificate_column,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='vendorprofile',
                    name='tax_certificate',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='type',
            field=models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], default='company', max_length=20),
        ),
    ]
