# Generated by Django 5.2.9 on 2026-01-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0023_remove_vendorprofile_tax_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='approval_state',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('REQUIRES_CHANGES', 'Requires Changes'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked')], default='PENDING', help_text='ISO 27001 compliant vendor approval state', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Legacy field - use approval_state instead'),
        ),
    ]
