# Generated by Django 5.2.9 on 2026-01-04 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0024_vendorprofile_approval_state_and_more'),
        ('parts', '0024_city_country_alter_cityarea_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.cityarea'),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='city_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.cityarea'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.city'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.country'),
        ),
        migrations.AlterField(
            model_name='vendorapplication',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.city'),
        ),
        migrations.AlterField(
            model_name='vendorapplication',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.country'),
        ),
    ]
