# Generated by Django 5.0.1 on 2026-01-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0025_address_city_area_vendorapplication_city_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city_area',
        ),
        migrations.RemoveField(
            model_name='vendorapplication',
            name='city_area',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendorapplication',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendorapplication',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
