# Generated by Django 5.2.9 on 2026-01-08 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0026_remove_address_city_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, help_text='Name of the bank account holder', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_details_verified',
            field=models.BooleanField(default=False, help_text='Whether bank details have been verified by an admin'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_verification_date',
            field=models.DateTimeField(blank=True, help_text='When bank details were verified', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin who verified the bank details', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_vendor_banks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='iban',
            field=models.CharField(blank=True, help_text='International Bank Account Number', max_length=50, null=True),
        ),
    ]
