# Generated by Django 5.2.9 on 2026-01-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0027_vendorprofile_bank_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='plant',
            field=models.CharField(blank=True, help_text='Plant / City location', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='storage_location',
            field=models.CharField(blank=True, help_text='Storage location / Area', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='warehouse_number',
            field=models.CharField(blank=True, help_text='Warehouse identifier', max_length=100, null=True),
        ),
    ]
